export const IpcChannel = {
  getEnvironment: "environment:get",
  listReminders: "reminders:list",
  createReminder: "reminders:create",
  updateReminder: "reminders:update",
  deleteReminder: "reminders:delete",
  completeReminder: "reminders:complete",
  reopenReminder: "reminders:reopen",
  setDueDates: "reminders:set-due-dates",
  listTags: "tags:list",
  createTag: "tags:create",
  updateTag: "tags:update",
  deleteTag: "tags:delete",
  getSettings: "settings:get",
  updateSettings: "settings:update",
  remindersChanged: "reminders:changed",
  todayChanged: "clock:today-changed",
  navigate: "app:navigate",
} as const;
